### ISSUE TITLE
1. Swift Intro

### ISSUE THREAD

**Issue by uch1** [MakeSchool-Tutorials/Getting-Started-With-Swift-2018#1]
The challenges in each section of the tutorial look compact. It will be easy for students to follow it if the challenges were numbered or broken down into separate problems . E.g page 11 Classes-and-Struct challenge 
![screen shot 2018-06-28 at 2 21 38 pm](https://user-images.githubusercontent.com/20326529/42061412-f0705998-7ade-11e8-87f2-55f7ce01ea7a.png)

**Comment by dionlarson** [comment]
Looking closer, seems to be your theme that is causing it to be so hard to read...

<img width="944" alt="screenshot 2018-07-01 17 32 17" src="https://user-images.githubusercontent.com/1843883/42140472-cf9ab9d4-7d54-11e8-9556-408fe4a1d5fd.png">
